export function JokesList () {
    return(
        <>
        <ul className="jokes-list">
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>

        </ul>
        </>
    )
}