export function JokesList () {
    return(
        <>
        <ul>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>
            <li>t</li>

        </ul>
        </>
    )
}